FROM alpine:latest

ARG VERSION
ARG TARGETARCH
ARG TARGETVARIANT

RUN apk add --no-cache tzdata tini bash curl unzip ca-certificates gcompat libgcc libstdc++ iproute2

COPY scripts/download.sh /download.sh
RUN chmod +x /download.sh && /download.sh "$VERSION" "$TARGETARCH" "$TARGETVARIANT" && \
    rm -f /usr/local/bin/easytier-core /usr/local/bin/easytier-cli /usr/local/bin/easytier-web

COPY scripts/entrypoint_web.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Create config directory and web directory
RUN mkdir -p /web/logs

# Web ports
EXPOSE 11210
EXPOSE 11211
EXPOSE 22020

VOLUME /web

ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]
CMD [""]
